spring:
  application:
    name: keeper-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/measurementdb

Server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


