spring:
  application:
    name: zuul-service
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

#spring:
#  application:
#    name: zuul-service
#server:
#  port: 8083
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
#  instance:
#    preferIpAddress: true

zuul:
  routes:
    pie-service:
      path: /pie/**
      service-id: pie-service
    keeper-service:
      path: /keeper/**
      service-id: keeper-service