#spring:
#    application:
#        name: pie-service


spring:
    application:
        name: pie-service
kafka
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka

Server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
    instance:
        preferIpAddress: true

#eureka:
#    client:
#        serviceUrl:
#            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#        preferIpAddress: true

keeper-service:
    ribbon:
        eureka:
            enabled: true
        ServerListRefreshInterval: 1000